version: '3'

services:

  medusa:
    build:
      context: ./marketplace
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME:-marketplace}
    depends_on:
      - postgres
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./marketplace/.env.docker:/application/.env
    command: sh -c "npx medusa db:setup --db marketplace && yarn dev"
    networks:
      - internal

networks:
  internal:
    external: true